// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Prisma 7 removed the separate directUrl config option - the CLI (migrate/db seed/etc.)
  // always uses this single `url`. Point it at the session pooler / direct connection so
  // schema operations work reliably. The running app is unaffected - it builds its own
  // @prisma/adapter-pg connection from DATABASE_URL directly in lib/prisma.ts, so it can
  // still use the transaction pooler for better connection scaling.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
